#cloud-config
package_upgrade: true
packages:
- nfs-utils
runcmd:
- mkdir -p /mnt/efs
- chown ubuntu:ubuntu /mnt/efs
- echo "file-system-id.efs.aws-region.amazonaws.com:/ /var/www/html/efs-mount-point nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
- mount -a -t nfs4
